<!doctype HTML>
<html>
    <head>
        <title>{$#title} :: Limb3 shop example application on &#123;&#123;macro&#125;&#125;</title>
        <meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>
        <link rel="stylesheet" type="text/css" href="/css/Header.css" />
        <link rel="stylesheet" type="text/css" href="/css/Menu.css" />
        <link rel="stylesheet" type="text/css" href="/css/Footer.css" />
        <link rel="stylesheet" type="text/css" href="/css/Style.css" />
        <link rel="stylesheet" type="text/css" href="/css/cp.css" />
        <link rel="stylesheet" type="text/css" href="/css/thickbox.css" />
        <link rel=stylesheet type="text/css" href="http://bits.limb-project.com/shop/styles/main.css"/>
    </head>
    
    <body>
        <header id="header">
            <section class="center">
                <img src="http://bits.limb-project.com/shop/images/logo.limb.gif"  width='384' height='46' alt='logo.limb' id='logo'/>
                <div id="limb_links"><a href="http://limb-project.com">limb-project.com</a>&nbsp;|&nbsp;<a href="http://bits.limb-project.com">bits.limb-project.com</a></div>
            </section>
        </header>

        <section id="center">
            <div id="wrapper" >
                <div id="container">
                    <article id="content">
                        <h1>{$#title}</h1>
                        {{include file='flash_box.phtml'/}}
                        
                        {{slot id='content_zone'/}}
                    </article>
                </div>

                <aside id="sidebar">
                    <nav id="navigation">
                        <ul>
                            <li><a href="/product/">Products</a></li>
                            <li><a href="/cart/">Your Cart</a></li>
                        </ul>
                    </nav>

                    <dl id="profile">
                        <dt>Profile</dt>
                        <dd>
                            {{include file="user/include/profile_box.phtml" user="$#toolkit.user"/}}
                        </dd>
                    </dl>
                </aside>
            </div>
        </section>
    </body>
</html>
