<?php $this->title = 'Login'; ?>
{{wrap with='front_page_layout.phtml' into='content_zone'}}
    {{form method='POST' id='login_form'}}
        {{include file='_admin/form_errors.phtml'/}}
        <table class="contentTable">
            <tr class="field">
                <td class="tdCaption">
                    Login:
                </td>
                <td>
                    {{input type='text' name='login' id='login' title='Login' class='input'/}}
                </td>
            </tr>
            <tr class="field">
                <td class="tdCaption">
                    Password:
                </td>
                <td>
                    {{input type='password' name='password' id='password' title='Password' class='input' /}}
                </td>
            </tr>
            <tr>
                <td colspan="2" class="tdCaption">
                    <input type="submit" class="button" name="submit" value="Enter" />
                </td>
            </tr>
        </table>
    {{/form}}
{{/wrap}}
