<? $this->title = 'Registration'; ?>
{{wrap with="front_page_layout.phtml" in="content_zone"}}
    
    {{form id='register_form' name='register_form' method='post'}}
        {{include file='user/include/form_fileds.phtml'/}}
            <tr>
                <td class="tdCaption">
                    Password:
                </td>
                <td class="required field">
                    {{input name='password' type='text' title='Password' error_class='error' required='required' /}}
                </td>
            </tr>
            <tr>
                <td class="tdCaption">
                    Repeat password:
                </td>
                <td class="required field">
                    {{input name='repeated_password' type='text' title='Repeat password' error_class='error'/}}
                </td>
            </tr>
            <tr>
                <td colspan="2" class="tdCaption"> 
                    <input id='register' type='submit' value='Register'/>
                </td>
            </tr>
        </table>
    {{/form}}
{{/wrap}}
