<? $this->title = 'Registration'; ?>
{{wrap with="front_page_layout.phtml" in="content_zone"}}
    
    {{form id='register_form' name='register_form' method='post'}}

        {{include file='_admin/form_errors.phtml'/}}
        
        <table class="contentTable">
            <tr>
                <td class="tdCaption">
                    Login:
                </td>
                <td class="required field">
                    {{input name='login' type='text' title='Login' required='required' /}}
                </td>
            </tr>
            <tr>
                <td class="tdCaption">
                    Name:
                </td>
                <td class="required field">
                    {{input name='name' type='text' title='Name'/}}
                </td>
            </tr>
            <tr>
                <td class="tdCaption">
                    Email:
                </td>
                <td class="required field">
                    {{input name='email' type='email' title='Email' error_class='error' required='required' /}}
                </td>
            </tr>
            <tr>
                <td class="tdCaption">
                    Password:
                </td>
                <td class="required field">
                    {{input name='password' type='text' title='Password' error_class='error' required='required' /}}
                </td>
            </tr>
            <tr>
                <td class="tdCaption">
                    Repeat password:
                </td>
                <td class="required field">
                    {{input name='repeated_password' type='text' title='Repeat password' error_class='error'/}}
                </td>
            </tr>
            <tr>
                <td class="tdCaption">
                    Delivery address:
                </td>
                <td class="field">
                    {{textarea name="address" id='address' type="text" title="Delivery address"/}}
                </td>
            </tr>
            <hr/>
            <tr>
                <td colspan="2" class="tdCaption"> 
                    <input id='register' type='submit' value='Register'/>
                </td>
            </tr>
        </table>
    {{/form}}
{{/wrap}}
