<!doctype html>
<html>
    <head>
        <title>Limb3 tutorial</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="stylesheet" type="text/css" href="/css/Header.css" />
        <link rel="stylesheet" type="text/css" href="/css/Menu.css" />
        <link rel="stylesheet" type="text/css" href="/css/Footer.css" />
        <link rel="stylesheet" type="text/css" href="/css/Style.css" />        
    </head>
    <body bgcolor="#FFFFFF" text="#000000" >

        <h1>Create news</h1>

            {{form id='news_form' name='news_form' method='post'}}
                <table class="contentTable">
                    <tr>
                        <td class='tdCaption'>
                            Title:
                        </td>                    
                        <td>
                            {{input name='title' type='text' size='60' title='Title'/}}
                        </td>                        
                    </tr>
                    <tr>
                        <td class='tdCaption'>
                            Date:
                        </td>
                        <td>
                            {{input name='date' type='text' size='15' title='Date'/}}
                        </td>
                    </tr>
                    <tr>
                        <td class='tdCaption'>
                            Annotation:
                        </td>
                        <td>
                            {{textarea name='annotation' rows='2' cols='40' title='Annotation'/}}
                        </td>
                    </tr>
                    <tr>
                        <td class='tdCaption'>
                            Content:
                        </td>
                        <td>
                            {{textarea name='content' rows='5' cols='40'/}}
                        </td>
                    </tr>
                    <tr>
                        <td colspan='2' class='tdCaption'>
                            {{input type='submit' value='Create'/}}
                        </td>
                    </tr>
                </table>
            {{/form}}

    </body>
</html>
